# alias l='ls -Xlah --time-style=+"%Y-%m-%d" --color=auto -F'
alias -g latest='*(om[1])'
alias :q='exit'
alias cal='cal -3m'
alias cls='clear'
alias grep='grep --color=always'
alias l='exa -lah'
alias mp='mpc toggle'
alias o='open .'
alias rf='source $HOME/.zshrc'
alias tmux='tmux -2'
alias update='sudo softwareupdate -i -a; brew update; brew upgrade; brew cleanup; brew cask upgrade; npm install npm -g; npm update -g; vim +PlugUpdate +qall'
alias v='nvim'
alias vim='nvim'
